# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pods-Register_Tests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pods-Register_Tests

end

target 'Register' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Register

end
